### ISSUE TITLE
Building multiarch images

### ISSUE THREAD

**Issue by mocdaniel** [managemeals/manage-meals-web#2]
Many people who self-host applications run on SBCs, e.g. Raspberry Pis. Those use ARM chips, so the currently available images with `amd64` architecture crash and won't work.

Could we adapt the GHA pipelines in the affected repositories to build multi arch images?

[There are existing GitHub Actions for these workflows](https://docs.docker.com/build/ci/github-actions/multi-platform/).

I can go ahead and open related PRs in the different affected repositories, if wanted.

**Comment by hilmarp** [comment]
Thanks! Sorry I've just been really busy. I added the multiarch steps in the GHA pipelines.
